### ISSUE TITLE
API: detect colony for 96 well plate returns too much data to plot

### ISSUE THREAD

**Issue by Endimion75** [local-minimum/scanomatic#120]
When I detect colonies on a 96 well plate, I get back an array of 213x209 values describing the colony.

This is too much data and it is not feasible for a user to mark so many points.  Also, it takes to much space to render all this points in an intractable fashion.

We need to find a better solution!  User interactivity may not be an option ... 

Attached screen shot.

![213x209 sc](https://cloud.githubusercontent.com/assets/14052981/25475591/8dd1425e-2b37-11e7-9816-5ecd54756bbd.png)

**Comment by local-minimum** [comment]
We are considering the following

The results should be plotted like an image and not with intractable pixels.

The UI should handle the user drawing a circle based on a `center` and a `radius` and send this to and endpoint.

There will be endpoints for

* Clear detection (set everything to background)
* Set circle (center, radius) to blob/background/not-used.

`center` should be a pixel coordinate in floats and `radius` a distance in float.

The endpoint would deliver the same type of detection mask data as the original detection did.

For rough implementation the user would probably need the to do the following:

1. Clear detection
2. Set circle a bit larger than colony to `not-used`.
3. Set circle(s) for colony to `blob`.

This should be doable on UI side and the users won't go crazy.

**Comment by local-minimum** [comment]
After reviewing the options we think this is best handled entirely on the client side.
Our suggestion is to make a simple painting app that "paints" all pixels in an area (circle of certain size). And by paint, I mean change the status of the pixel as `blob`/`background`/`not-used`.
Since the image is in gray-scale each type (`blob`/`background`/`not-used`) could have it's own distinct color channel (hue and saturation) and the value could be the gray-scale intensity. That should make it very clear for the user how the detection worked and quite manageable app to make. There should be no need for undo, but you should probably have a few different sized brushes (from 1x1 px up to larger) and a clear/make everything `background`.
