### ISSUE TITLE
setup.py fails unless `~/.scan-o-matic` exists

### ISSUE THREAD

**Issue by pmagwene** [local-minimum/scanomatic#124]
System: Ubuntu 16.04, Anaconda python 4.4 (Python 2.7)

`python setup.py install --user` fails unless `~/.scan-o-matic `directory already exists

**Comment by local-minimum** [comment]
Hi, I've got 2 days of holidays, but I'll check this Wednesday. I believe there's a fix in the master branch but it's really not recommended to stray from the releases as the code between releases has yet to be verified that it doesn't interrupt or cause problems for the scanning. But, just to be sure, you were installing from the latest release when you encountered this issue right? And you also managed to create said directory so that you could continue with the installation?

**Comment by pmagwene** [comment]
Yes, if `~/.scan-o-matic` is created manually, installation proceeds.  However, note [Issue 125](https://github.com/local-minimum/scanomatic/issues/125) is also a blocker to a properly working install.

**Comment by local-minimum** [comment]
Great then this will be fixed as soon as we have setup so we can verify that system is stable for scanning.
